### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by RohitVerma882** [green-green-avk/libusb-1.0.23-android-helper-service-patch#1]
Please update libusb library or provide patches

**Comment by green-green-avk** [comment]
Done.

* <https://github.com/green-green-avk/libusb/tree/v1.0.26-android-libusbmanager>
* <https://github.com/green-green-avk/AnotherTerm-scripts/blob/master/install-patched-libusb-1.0.26.sh>
* <https://green-green-avk.github.io/AnotherTerm-docs/installing-libusb-for-nonrooted-android.html#main_content>

Please, confirm.

**Comment by RohitVerma882** [comment]
How to use LibUsbManager.java?

**Comment by green-green-avk** [comment]
Do you want to create your own Android app?

If so, here is an example:

<https://github.com/green-green-avk/AnotherTerm/blob/9dba92cda68b6c3cf819579d8f2a0a51a7ac5f29/app/src/main/java/green_green_avk/anotherterm/App.java#L104-L105>

<https://github.com/green-green-avk/AnotherTerm/blob/9dba92cda68b6c3cf819579d8f2a0a51a7ac5f29/app/src/main/java/green_green_avk/anotherterm/App.java#L126>

<https://github.com/green-green-avk/AnotherTerm/blob/9dba92cda68b6c3cf819579d8f2a0a51a7ac5f29/app/src/main/AndroidManifest.xml#L25-L26>

**Comment by RohitVerma882** [comment]
I'm tried it,  but not working

**Comment by RohitVerma882** [comment]
I need some help from you, what is your telegram userid?

**Comment by RohitVerma882** [comment]
> Do you want to create your own Android app?
> 
> If so, here is an example:
> 
> https://github.com/green-green-avk/AnotherTerm/blob/9dba92cda68b6c3cf819579d8f2a0a51a7ac5f29/app/src/main/java/green_green_avk/anotherterm/App.java#L104-L105
> 
> https://github.com/green-green-avk/AnotherTerm/blob/9dba92cda68b6c3cf819579d8f2a0a51a7ac5f29/app/src/main/java/green_green_avk/anotherterm/App.java#L126
> 
> https://github.com/green-green-avk/AnotherTerm/blob/9dba92cda68b6c3cf819579d8f2a0a51a7ac5f29/app/src/main/AndroidManifest.xml#L25-L26

It's working, but application crashed or app closed automatically I don't know why my application closed when I click ```OK``` usb open popup dialog.

**Comment by RohitVerma882** [comment]
Now it's working, problem fixed by closing ParcelFileDescriptor after sending fd
